Updated script for Flutter v1.7.8+hotfix.3
fbsb/homebrew-flutter pull request #3
Opened 2019-07-10 13:31 UTC by akassharjun

Please check if the SHA256 sum is correct.

2019-07-11 19:46 UTC, fbsb requested changes

2019-07-11 19:46 UTC, fbsb commented on Casks/flutter.rb
> +  version "v1.7.8+hotfix.3"
Could you please remove the `v` prefix from the version? It's already included in the URL and is not needed here.

2019-07-11 19:46 UTC, fbsb commented on Casks/flutter.rb
> +  sha256 "800db14570c5dd9e4e0d3b403ebd9579cd09226c004239a880470eab438f0872"
The correct sum is `1bd5d165c79efebfba39e4602d6e07e74b40798630eb7173caedf0f664c53035`. Could you please update that aswell?

2019-07-11 19:48 UTC, fbsb commented
Also you need to rebase to resolve the conflicts

2019-07-13 13:36 UTC, akassharjun commented
Done

2019-07-14 12:24 UTC, fbsb approved these changes

2019-07-14 12:25 UTC, merged

2019-07-14 12:25 UTC, fbsb commented
Great! Thank you!